### ISSUE TITLE
Historisk opslag virker ikke helt endnu... 

### ISSUE THREAD

**Issue by Montago** [Montago/dmr-webservice#1]

**Comment by ontranet** [comment]
Hej Martin,

Løsningen virker vist ikke mere. Kan det skyldes at skat har ændret i deres frontend?

**Comment by Montago** [comment]
Hej Peter..

Hvis Motorregistret har ændret siden kan det sagtens ske at der går ged i scraperen. 

Jeg må lige kigge på det når jeg har lidt tid.

**Comment by ontranet** [comment]
Super, tak for svar

Peter Cort Larsen
Ontranet
Saltværksvej 187
2770 Kastrup
42700100

Fra: Martin Kirk
Sendt: 17. januar 2021 14:57
Til: Montago/dmr-webservice
Cc: Peter Cort Larsen; Comment
Emne: Re: [Montago/dmr-webservice] Historisk opslag virker ikke heltendnu... (#1)

Hej Peter..
Hvis Motorregistret har ændret siden kan det sagtens ske at der går ged i scraperen.
Jeg må lige kigge på det når jeg har lidt tid.

**Comment by Montago** [comment]
> Super, tak for svar 

Jeg har fixet koden nu .. det tog kun et par minutter, men fik først tid til det nu :)

**Comment by Montago** [comment]
Historisk opslag virker som det skal.. tror jeg ..

**Comment by ontranet** [comment]
Spændende, glæder mig til at se på det18. feb. 2021 13.33 skrev Martin Kirk <notifications@github.com>:



Super, tak for svar



Jeg har fixet koden nu .. det tog kun et par minutter, men fik først tid til det nu :)
